# Generated by Django 5.0.6 on 2024-07-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='zipcode',
            field=models.CharField(default=2032, max_length=20),
            preserve_default=False,
        ),
    ]
