# Generated by Django 5.0.6 on 2024-07-15 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_candidate_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='candidates',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='main_app.job')),
            ],
            options={
                'unique_together': {('job', 'candidate')},
            },
        ),
    ]
