# Generated by Django 5.0.6 on 2024-07-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_remove_job_candidates_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='description',
            field=models.CharField(default='No description provided', max_length=500),
            preserve_default=False,
        ),
    ]
